package ot

import (
	"encoding/json"
	"flag"
	"math/rand"
	"os"
	"path/filepath"
	"testing"
)

// The Go and TypeScript engines must agree byte for byte, or two clients will
// silently diverge in ways no single-language test can catch. These vectors are
// the contract between them: generated here, committed, and replayed by
// web/src/ot/vectors.test.ts.
//
// Regenerate with:
//
//	go test ./internal/ot -run TestGoldenVectors -write-vectors
//
// A regeneration that changes existing cases means a wire-format change, and
// every client in the wild is now incompatible. That should be a deliberate,
// noticed event — which is the reason the file is committed rather than built.

var writeVectors = flag.Bool("write-vectors", false, "regenerate testdata/ot-vectors.json")

const vectorsPath = "../../testdata/ot-vectors.json"

type applyCase struct {
	Doc  string   `json:"doc"`
	Op   *OpSeq   `json:"op"`
	Want string   `json:"want"`
	Note string   `json:"note,omitempty"`
	_    struct{} `json:"-"`
}

type composeCase struct {
	Doc  string `json:"doc"`
	A    *OpSeq `json:"a"`
	B    *OpSeq `json:"b"`
	Want string `json:"want"`
}

type transformCase struct {
	Doc    string `json:"doc"`
	A      *OpSeq `json:"a"`
	B      *OpSeq `json:"b"`
	APrime *OpSeq `json:"aPrime"`
	BPrime *OpSeq `json:"bPrime"`
	Want   string `json:"want"`
}

type vectorFile struct {
	Note      string          `json:"note"`
	Unit      string          `json:"unit"`
	Apply     []applyCase     `json:"apply"`
	Compose   []composeCase   `json:"compose"`
	Transform []transformCase `json:"transform"`
}

func buildVectors(t *testing.T) vectorFile {
	t.Helper()
	// Fixed seed: the vectors must be reproducible, or "regenerate" would churn
	// the file on every run and hide real changes in the noise.
	rng := rand.New(rand.NewSource(20260905))

	out := vectorFile{
		Note: "Generated by internal/ot/vectors_test.go. The Go and TypeScript OT " +
			"engines must both reproduce every case exactly.",
		Unit: "All offsets and lengths are UTF-8 byte counts.",
	}

	// Hand-written cases first: these pin the behaviour that matters for
	// Persian specifically, and stay readable in a diff.
	fixed := []struct {
		doc, want, note string
		build           func(*OpSeq)
	}{
		{"", "سلام", "insert Persian into an empty document", func(o *OpSeq) { o.Insert("سلام") }},
		{"سلام", "", "delete a 4-character, 8-byte document", func(o *OpSeq) { o.Delete(8) }},
		{"میروم", "می‌روم", "insert a ZWNJ inside a word", func(o *OpSeq) { o.Retain(4); o.Insert(zwnj); o.Retain(6) }},
		{"می‌روم", "میروم", "delete a ZWNJ from inside a word", func(o *OpSeq) { o.Retain(4); o.Delete(3); o.Retain(6) }},
		{"a😀b", "ab", "delete a 4-byte astral character", func(o *OpSeq) { o.Retain(1); o.Delete(4); o.Retain(1) }},
		{"مخلوط mixed", "مخلوط متن", "replace across a bidi boundary", func(o *OpSeq) { o.Retain(11); o.Delete(5); o.Insert("متن") }},
	}
	for _, f := range fixed {
		op := New()
		f.build(op)
		got, err := op.Apply(f.doc)
		if err != nil {
			t.Fatalf("fixed case %q: %v", f.note, err)
		}
		if got != f.want {
			t.Fatalf("fixed case %q: got %q, want %q", f.note, got, f.want)
		}
		out.Apply = append(out.Apply, applyCase{Doc: f.doc, Op: op, Want: got, Note: f.note})
	}

	for len(out.Apply) < 80 {
		doc := randomDoc(rng)
		op := randomOp(rng, doc)
		want, err := op.Apply(doc)
		if err != nil {
			t.Fatalf("generate apply case: %v", err)
		}
		out.Apply = append(out.Apply, applyCase{Doc: doc, Op: op, Want: want})
	}

	for len(out.Compose) < 60 {
		doc := randomDoc(rng)
		a := randomOp(rng, doc)
		mid, err := a.Apply(doc)
		if err != nil {
			t.Fatalf("generate compose case: %v", err)
		}
		b := randomOp(rng, mid)
		want, err := b.Apply(mid)
		if err != nil {
			t.Fatalf("generate compose case: %v", err)
		}
		out.Compose = append(out.Compose, composeCase{Doc: doc, A: a, B: b, Want: want})
	}

	for len(out.Transform) < 100 {
		doc := randomDoc(rng)
		a, b := randomOp(rng, doc), randomOp(rng, doc)
		aPrime, bPrime, err := Transform(a, b)
		if err != nil {
			t.Fatalf("generate transform case: %v", err)
		}
		ab, err := Compose(a, bPrime)
		if err != nil {
			t.Fatalf("generate transform case: %v", err)
		}
		want, err := ab.Apply(doc)
		if err != nil {
			t.Fatalf("generate transform case: %v", err)
		}
		out.Transform = append(out.Transform,
			transformCase{Doc: doc, A: a, B: b, APrime: aPrime, BPrime: bPrime, Want: want})
	}

	return out
}

func TestGoldenVectors(t *testing.T) {
	if *writeVectors {
		v := buildVectors(t)
		blob, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			t.Fatalf("marshal vectors: %v", err)
		}
		blob = append(blob, '\n')
		if err := os.MkdirAll(filepath.Dir(vectorsPath), 0o755); err != nil {
			t.Fatalf("create testdata dir: %v", err)
		}
		if err := os.WriteFile(vectorsPath, blob, 0o644); err != nil {
			t.Fatalf("write vectors: %v", err)
		}
		t.Logf("wrote %d apply, %d compose and %d transform cases to %s",
			len(v.Apply), len(v.Compose), len(v.Transform), vectorsPath)
		return
	}

	blob, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Skipf("no vector file yet (%v); run with -write-vectors", err)
	}

	var v vectorFile
	if err := json.Unmarshal(blob, &v); err != nil {
		t.Fatalf("decode vectors: %v", err)
	}
	if len(v.Apply) == 0 || len(v.Compose) == 0 || len(v.Transform) == 0 {
		t.Fatal("vector file is missing whole sections")
	}

	for i, c := range v.Apply {
		got, err := c.Op.Apply(c.Doc)
		if err != nil {
			t.Fatalf("apply[%d] (%s): %v", i, c.Note, err)
		}
		if got != c.Want {
			t.Fatalf("apply[%d] (%s): got %q, want %q", i, c.Note, got, c.Want)
		}
	}

	for i, c := range v.Compose {
		ab, err := Compose(c.A, c.B)
		if err != nil {
			t.Fatalf("compose[%d]: %v", i, err)
		}
		got, err := ab.Apply(c.Doc)
		if err != nil {
			t.Fatalf("compose[%d] apply: %v", i, err)
		}
		if got != c.Want {
			t.Fatalf("compose[%d]: got %q, want %q", i, got, c.Want)
		}
	}

	for i, c := range v.Transform {
		aPrime, bPrime, err := Transform(c.A, c.B)
		if err != nil {
			t.Fatalf("transform[%d]: %v", i, err)
		}
		// The transformed operations themselves are part of the contract, not
		// just the document they produce: a client applies b' directly.
		if aPrime.String() != c.APrime.String() {
			t.Fatalf("transform[%d]: a' = %s, want %s", i, aPrime, c.APrime)
		}
		if bPrime.String() != c.BPrime.String() {
			t.Fatalf("transform[%d]: b' = %s, want %s", i, bPrime, c.BPrime)
		}
		ab, err := Compose(c.A, bPrime)
		if err != nil {
			t.Fatalf("transform[%d] compose: %v", i, err)
		}
		got, err := ab.Apply(c.Doc)
		if err != nil {
			t.Fatalf("transform[%d] apply: %v", i, err)
		}
		if got != c.Want {
			t.Fatalf("transform[%d]: got %q, want %q", i, got, c.Want)
		}
	}
}
